# Generated by Django 3.2 on 2021-04-19 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('trans_id', models.AutoField(db_column='Trans_id', primary_key=True, serialize=False)),
                ('item', models.CharField(db_column='Item', max_length=1000)),
                ('qty', models.CharField(blank=True, db_column='Qty', max_length=10, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
                ('trans_type', models.CharField(db_column='Trans_type', max_length=10)),
                ('trans_date', models.DateTimeField(db_column='Trans_date', default=datetime.datetime(2021, 4, 19, 16, 9, 27, 799891))),
            ],
            options={
                'db_table': 'transaction_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('businessname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=70)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=200)),
                ('datejoined', models.DateTimeField(default=datetime.datetime(2021, 4, 19, 16, 9, 27, 799891))),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
